-- Seed: initial peptide list
-- Run in Supabase SQL editor after migrations 0001–0003

insert into peptides (slug, name, aliases, cas_number, molecular_weight, mechanism, category, indications_tags, legal_status, overview)
values

('bpc-157',
 'BPC-157',
 array['Body Protection Compound 157','PL 14736'],
 '137525-51-0',
 1419.5,
 'Upregulates growth factor receptors (VEGFR2, EGFR); promotes angiogenesis, collagen synthesis, and nitric oxide production; modulates dopamine and serotonin pathways.',
 'research',
 array['tendon healing','wound healing','gut health','neuroprotection','inflammation'],
 '{"FDA": "not approved", "status": "research only"}',
 'BPC-157 is a synthetic 15-amino-acid peptide derived from a protective protein found in gastric juice. It is one of the most studied research peptides for tissue repair, with robust animal evidence across musculoskeletal, gastrointestinal, and neurological models.'
),

('tb-500',
 'TB-500',
 array['Thymosin Beta-4','Tβ4'],
 '77591-33-4',
 4921.4,
 'Sequesters G-actin; promotes cell migration, angiogenesis, and anti-inflammation via upregulation of actin dynamics and Akt/mTOR signalling.',
 'research',
 array['muscle repair','wound healing','cardiac protection','hair growth','inflammation'],
 '{"FDA": "not approved", "status": "research only"}',
 'TB-500 is a synthetic analogue of the naturally occurring thymosin beta-4 peptide. Strong preclinical evidence supports roles in wound healing and cardiac protection; limited human data available.'
),

('ghk-cu',
 'GHK-Cu',
 array['Copper Peptide GHK','Glycyl-L-histidyl-L-lysine copper'],
 '89030-95-5',
 340.4,
 'Copper-chelating tripeptide that activates wound-healing genes, stimulates collagen and glycosaminoglycan synthesis, and exhibits antioxidant and anti-inflammatory activity.',
 'research',
 array['skin repair','wound healing','hair growth','anti-aging','collagen synthesis'],
 '{"FDA": "not approved for systemic use", "status": "cosmetic ingredient approved (topical)"}',
 'GHK-Cu is an endogenous copper-binding tripeptide with broad tissue-remodelling effects. Widely used in cosmetics; systemic research-use applications are investigational.'
),

('semaglutide',
 'Semaglutide',
 array['Ozempic','Wegovy','Rybelsus'],
 '910463-68-2',
 4113.6,
 'GLP-1 receptor agonist; augments glucose-dependent insulin secretion, suppresses glucagon, slows gastric emptying, and reduces appetite via hypothalamic pathways.',
 'both',
 array['type 2 diabetes','obesity','weight loss','cardiovascular risk reduction','NAFLD'],
 '{"FDA": "approved (Ozempic T2D 2017, Wegovy obesity 2021, Rybelsus oral 2019)", "EU": "approved", "TGA": "approved"}',
 'Semaglutide is an FDA-approved GLP-1 receptor agonist with landmark RCT evidence for weight loss (STEP trials) and cardiovascular outcomes (SUSTAIN-6, SELECT). The highest-evidence peptide in the database.'
),

('tirzepatide',
 'Tirzepatide',
 array['Mounjaro','Zepbound'],
 '2023788-19-8',
 4813.5,
 'Dual GIP and GLP-1 receptor agonist; combines incretin effects for superior glycaemic control and weight reduction compared to GLP-1 monotherapy.',
 'both',
 array['type 2 diabetes','obesity','weight loss','NAFLD','cardiovascular risk'],
 '{"FDA": "approved (Mounjaro T2D 2022, Zepbound obesity 2023)", "EU": "approved"}',
 'Tirzepatide is an FDA-approved dual incretin agonist. SURMOUNT trials demonstrated up to 22% body-weight reduction, currently the highest efficacy in any approved obesity pharmacotherapy.'
),

('melanotan-ii',
 'Melanotan II',
 array['MT-2','MTII'],
 '121062-08-6',
 1024.2,
 'Non-selective melanocortin receptor agonist (MC1R–MC5R); induces melanogenesis, sexual arousal (MC4R), and appetite suppression.',
 'research',
 array['tanning','sexual dysfunction','erectile dysfunction','libido','appetite'],
 '{"FDA": "not approved", "status": "research only — not for human use in most jurisdictions"}',
 'Melanotan II is a cyclic lactam analogue of alpha-MSH. Despite no regulatory approval, it is widely misused. Adverse events including melanoma progression, cardiovascular effects, and priapism are documented in case reports.'
),

('pt-141',
 'PT-141',
 array['Bremelanotide','Vyleesi'],
 '189691-06-3',
 1025.2,
 'Melanocortin MC3R/MC4R agonist acting centrally in the CNS to increase sexual desire, independent of vascular mechanisms.',
 'both',
 array['female sexual dysfunction','HSDD','sexual arousal','libido'],
 '{"FDA": "approved (Vyleesi for HSDD in premenopausal women, 2019)"}',
 'PT-141 (bremelanotide) is FDA-approved for hypoactive sexual desire disorder (HSDD) in premenopausal women. Off-label research use in men for sexual dysfunction is ongoing.'
),

('ipamorelin',
 'Ipamorelin',
 array['NNC 26-0161'],
 '170851-70-4',
 711.9,
 'Selective ghrelin/GHS-R1a receptor agonist; stimulates pulsatile GH release from pituitary with minimal effect on cortisol or prolactin.',
 'research',
 array['growth hormone deficiency','muscle growth','fat loss','anti-aging','recovery'],
 '{"FDA": "not approved", "status": "research only"}',
 'Ipamorelin is a selective GHRP with a clean safety profile in animals. Frequently combined with CJC-1295. Limited human clinical data; preclinical data supports GH secretagogue effects.'
),

('cjc-1295',
 'CJC-1295',
 array['DAC:GRF','CJC-1295 DAC'],
 '863288-34-0',
 3368.0,
 'GHRH analogue with drug-affinity complex (DAC) technology extending half-life to ~8 days; stimulates sustained GH and IGF-1 elevation.',
 'research',
 array['growth hormone deficiency','muscle growth','fat loss','anti-aging'],
 '{"FDA": "not approved", "status": "research only"}',
 'CJC-1295 is a modified GHRH analogue designed for extended action. Phase I/II human data demonstrated dose-dependent GH/IGF-1 increases. Commonly used in research in combination with ipamorelin.'
),

('sermorelin',
 'Sermorelin',
 array['GHRH 1-29','Geref'],
 '86168-78-7',
 3358.0,
 'Synthetic analogue of the first 29 amino acids of endogenous GHRH; stimulates physiological pulsatile GH release via pituitary GHRH receptors.',
 'both',
 array['growth hormone deficiency','anti-aging','sleep','body composition'],
 '{"FDA": "previously approved (Geref — withdrawn from market 2008, not for safety reasons)", "status": "compounded use in anti-aging clinics"}',
 'Sermorelin was FDA-approved for GH deficiency in children. Withdrawn due to commercial reasons. Widely used in compounding for adult GH optimisation, with reasonable safety data from original approval studies.'
),

('tesamorelin',
 'Tesamorelin',
 array['Egrifta','TH9507'],
 '218949-48-9',
 5135.0,
 'Stabilised GHRH analogue; selectively reduces visceral adipose tissue via GH/IGF-1 axis stimulation, with minimal effect on glucose.',
 'both',
 array['HIV-associated lipodystrophy','visceral fat','body composition','NAFLD'],
 '{"FDA": "approved (Egrifta for HIV-associated lipodystrophy, 2010)"}',
 'Tesamorelin is FDA-approved for visceral fat reduction in HIV-associated lipodystrophy. Phase III trials demonstrated significant VAT reduction. Off-label use in metabolic syndrome and NAFLD is under investigation.'
),

('hexarelin',
 'Hexarelin',
 array['Examorelin','EP 23905'],
 '140703-51-1',
 887.1,
 'Potent synthetic hexapeptide GHS-R1a agonist; the most potent GHRP for GH release but also significantly raises cortisol and prolactin.',
 'research',
 array['growth hormone','cardiac protection','muscle growth','GH deficiency'],
 '{"FDA": "not approved", "status": "research only"}',
 'Hexarelin is the most potent synthetic GHRP but its cortisol and prolactin elevation limits clinical utility. Intriguing cardioprotective effects via CD36 receptor binding are under investigation independent of GH effects.'
),

('ghrp-2',
 'GHRP-2',
 array['Pralmorelin','KP-102'],
 '158861-67-7',
 817.9,
 'Synthetic hexapeptide GHS-R1a agonist; potent GH secretagogue with moderate cortisol and prolactin elevation.',
 'research',
 array['GH deficiency','body composition','muscle growth','appetite'],
 '{"FDA": "not approved (used as a diagnostic agent in some countries)", "Japan": "approved as diagnostic (Macimorelin precursor)"}',
 'GHRP-2 is a well-characterised GH secretagogue peptide. Approved as a diagnostic provocative agent in some jurisdictions. Used in research for body-composition and GH-axis studies.'
),

('epithalon',
 'Epithalon',
 array['Epitalon','Epithalone','Ala-Glu-Asp-Gly'],
 '307297-39-8',
 390.3,
 'Synthetic tetrapeptide derived from epithalamin; proposed to activate telomerase (hTERT), regulate melatonin secretion, and modulate neuroendocrine function.',
 'research',
 array['anti-aging','telomere extension','sleep','longevity','cancer prevention'],
 '{"FDA": "not approved", "status": "research only"}',
 'Epithalon is a tetrapeptide developed by the St. Petersburg Institute of Bioregulation. Primarily Russian research; claims of telomerase activation and lifespan extension in animal models. Human evidence is very limited and methodologically weak.'
),

('selank',
 'Selank',
 array['TP-7','Selanc'],
 '129954-34-3',
 863.0,
 'Synthetic analogue of tuftsin (Thr-Lys-Pro-Arg); modulates GABA-A receptors and BDNF expression; anxiolytic without sedation or dependence.',
 'research',
 array['anxiety','nootropic','PTSD','depression','cognitive enhancement'],
 '{"FDA": "not approved", "Russia": "approved (Selank nasal spray)", "status": "research only outside Russia/Ukraine"}',
 'Selank is a heptapeptide anxiolytic approved in Russia for anxiety and asthenic conditions. Small RCTs from Russian institutions report anxiolytic and cognitive effects; independent replication is limited.'
),

('semax',
 'Semax',
 array['ACTH 4-7 Pro8-Gly9-Pro10'],
 '80714-61-0',
 657.8,
 'Synthetic ACTH fragment analogue; stimulates BDNF and NGF synthesis, modulates dopaminergic and serotonergic systems, neuroprotective.',
 'research',
 array['nootropic','neuroprotection','stroke recovery','ADHD','cognitive enhancement'],
 '{"FDA": "not approved", "Russia": "approved (nasal spray for stroke/cognitive disorders)", "status": "research only outside Russia"}',
 'Semax is a heptapeptide approved in Russia for ischaemic stroke and cognitive impairment. Evidence base largely from Russian clinical trials; independent replication and regulatory review outside Russia are absent.'
),

('thymosin-alpha-1',
 'Thymosin Alpha-1',
 array['Tα1','Thymalfasin','Zadaxin'],
 '62304-98-7',
 3108.5,
 'Naturally occurring thymic peptide; enhances T-cell maturation and function, augments NK cell activity, promotes dendritic cell differentiation, and upregulates TLR expression.',
 'both',
 array['immune modulation','hepatitis B','hepatitis C','cancer adjuvant','COVID-19','sepsis'],
 '{"FDA": "orphan drug designation (various)", "China": "approved (Zadaxin)", "Italy": "approved", "status": "approved in 35+ countries"}',
 'Thymosin alpha-1 is an endogenous immunomodulatory peptide approved in numerous countries for hepatitis B/C and as a cancer adjuvant. Substantial RCT evidence for immune restoration; studied extensively in COVID-19.'
),

('ll-37',
 'LL-37',
 array['Cathelicidin','hCAP18 active peptide','CAMP'],
 '154947-66-7',
 4493.3,
 'Human cathelicidin antimicrobial peptide; disrupts bacterial membranes, modulates TLR signalling, promotes wound healing, angiogenesis, and immune cell recruitment.',
 'research',
 array['antimicrobial','wound healing','inflammation','skin conditions','biofilm'],
 '{"FDA": "not approved", "status": "research only"}',
 'LL-37 is the only human cathelicidin, with potent broad-spectrum antimicrobial activity and immunomodulatory functions. Research interest spans wound healing, inflammatory skin disease, and infection. No approved clinical formulations.'
),

('kpv',
 'KPV',
 array['Lys-Pro-Val','α-MSH C-terminal tripeptide'],
 '66003-32-5',
 339.4,
 'C-terminal tripeptide of alpha-MSH; anti-inflammatory via MC1R activation and NF-κB inhibition; antimicrobial in gastrointestinal epithelium.',
 'research',
 array['gut inflammation','IBD','Crohns disease','wound healing','antimicrobial'],
 '{"FDA": "not approved", "status": "research only"}',
 'KPV is a tripeptide derived from alpha-MSH with potent anti-inflammatory and intestinal epithelial barrier-protective properties in rodent IBD models. Early-stage research; no human trials published.'
),

('aod-9604',
 'AOD-9604',
 array['Anti-Obesity Drug 9604','Tyr-hGH fragment 177-191'],
 '221231-10-3',
 1817.1,
 'Modified hGH fragment (177-191) that stimulates lipolysis and inhibits lipogenesis via beta-3 adrenergic receptor without IGF-1-mediated growth effects.',
 'research',
 array['fat loss','obesity','lipolysis','cartilage repair','osteoarthritis'],
 '{"FDA": "GRAS designation for food use", "TGA": "completed Phase III (obesity — did not meet primary endpoint)"}',
 'AOD-9604 completed Phase III trials for obesity in Australia but failed to meet its primary endpoint. Subsequently received FDA GRAS status. Preclinical evidence for cartilage repair has attracted secondary research interest.'
),

('dihexa',
 'Dihexa',
 array['PNB-0408','N-hexanoic-Tyr-Ile-(6) aminohexanoic amide'],
 null,
 452.6,
 'Hepatocyte growth factor (HGF) mimetic; binds pleiotrophin and activates HGF/MET receptor pathway; potently synaptogenic and pro-cognitive in rodent models.',
 'research',
 array['nootropic','Alzheimers','cognitive enhancement','neurodegeneration','synaptogenesis'],
 '{"FDA": "not approved", "status": "research only — no human trials"}',
 'Dihexa is an angiotensin-derived nootropic peptide developed at Washington State University. Rodent cognition data is striking but no human pharmacokinetic or safety data exist. Significant caution warranted.'
),

('vip',
 'VIP',
 array['Vasoactive Intestinal Peptide','Aviptadil'],
 '37221-79-7',
 3326.8,
 'Neuropeptide activating VPAC1/VPAC2 receptors; potent vasodilator, bronchodilator, anti-inflammatory, immunomodulatory, and circadian rhythm regulator.',
 'research',
 array['pulmonary hypertension','ARDS','COVID-19','SARS','erectile dysfunction','immune modulation'],
 '{"FDA": "approved (Aviptadil/RLF-100 for COVID-19 ARDS under EUA — expired)", "status": "investigational"}',
 'VIP is an endogenous neuropeptide with profound pulmonary vasodilatory and immunomodulatory effects. Aviptadil (synthetic VIP) received Emergency Use Authorization for COVID-19 ARDS. Phase III trials are ongoing for pulmonary arterial hypertension.'
),

('humanin',
 'Humanin',
 array['HN','HNG (potent analogue)'],
 '326579-58-2',
 2886.4,
 'Mitochondria-derived peptide (MOTS-c related); activates STAT3/MAPK and FPRL1 receptor; cytoprotective, insulin-sensitising, anti-apoptotic.',
 'research',
 array['longevity','neuroprotection','Alzheimers','metabolic syndrome','insulin sensitivity'],
 '{"FDA": "not approved", "status": "research only"}',
 'Humanin is a 21-amino-acid peptide encoded in the mitochondrial genome. Circulating levels decline with age. Preclinical data supports neuroprotective and metabolic effects; human interventional studies are early-stage.'
),

('mots-c',
 'MOTS-c',
 array['Mitochondrial ORF of the 12S rRNA type-c'],
 null,
 2174.5,
 'Mitochondria-derived peptide that translocates to the nucleus under metabolic stress; activates AMPK, enhances glucose uptake, improves insulin sensitivity, and regulates mitophagy.',
 'research',
 array['insulin resistance','obesity','longevity','exercise mimetic','metabolic syndrome'],
 '{"FDA": "not approved", "status": "research only"}',
 'MOTS-c is a mitochondrial-derived peptide whose plasma levels decline with age. Rodent studies show profound metabolic and lifespan effects. Early human observational and first-in-human dosing studies are emerging.'
);
